version: "2"

volumes:
  app-gems:
    driver: local

services:
  redis:
    container_name: 'word_counter_redis'
    image: redis:3.2.7-alpine
    mem_limit: 300m
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data

  elasticsearch:
    container_name: 'word_counter_elasticsearch'
    image: elasticsearch:5-alpine
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    mem_limit: 1g
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - '9200'
      - '9300'

  web:
    container_name: 'word_counter_web'
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - app
      - worker
    env_file:
      - app.local.env
    command: nginx -c /etc/nginx/nginx.conf
    volumes_from:
      - app
    ports:
      - "80:80"
      - "443:443"

  app: &app_base
    container_name: 'word_counter_app'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - app.local.env
    links:
      - elasticsearch
      - redis
    logging:
      options:
        max-size: "1g"
        max-file: "10"
    volumes:
      - ./etc/ssl/word_counter:/etc/ssl/word_counter
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/html:/etc/nginx/html
      - ./etc/nginx/word_counter.conf:/etc/nginx/conf.d/word_counter.conf
      - ./etc/nginx/conf.d/word_counter:/etc/nginx/conf.d/word_counter
      - ./config/cable.yml:/var/www/word_counter/config/cable.yml
      - ./config/config.yml:/var/www/word_counter/config/config.yml
      - ./config/database.yml:/var/www/word_counter/config/database.yml
      - ./config/elasticsearch.yml:/var/www/word_counter/config/elasticsearch.yml
      - ./config/redis.yml:/var/www/word_counter/config/redis.yml
      - ./config/secrets.yml:/var/www/word_counter/config/secrets.yml
      - ./config/puma.rb:/var/www/word_counter/config/puma.rb
      - ./config/puma-backup.rb:/var/www/word_counter/config/puma-backup.rb
      - ./shared/ssl:/var/www/ssl
      - ./shared/cache/assets:/var/www/word_counter/public/assets
      - ./shared/.well-known:/var/www/word_counter/public/.well-known
      - ./data/uploads:/var/www/word_counter/public/uploads
      - ./shared/cache/uploads-thumb:/var/www/cache/uploads-thumb
      - ./shared/system:/var/www/word_counter/public/system
      - ./log:/var/www/log
      - ./log:/var/www/word_counter/log
      - ./tmp:/var/www/word_counter/tmp
      - ./tmp/pids:/var/www/pids
      - ./tmp/pids:/var/www/word_counter/tmp/pids
      - .:/var/www/word_counter
      - app-gems:/usr/local/bundle
    command: bundle exec puma -C config/puma.rb
    ports:
      - "7000:7000"

  worker:
    <<: *app_base
    container_name: 'word_counter_worker'
    ports: []
    command: bundle exec sidekiq -e development -r ./config/environment.rb